import pkg from '/root/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.js';
const { chromium } = pkg;
const SLUG='reorc';
const b = await chromium.launch();
const ctx = await b.newContext({ storageState: './.state.json', locale:'zh-CN', viewport:{width:1440,height:900}, deviceScaleFactor:2 });
const p = await ctx.newPage();
await p.goto(`https://app.syfo.ai/s/${SLUG}/members`,{waitUntil:'networkidle',timeout:50000});
await p.waitForTimeout(3000);
await (await p.$('text=创建 Agent')).click(); await p.waitForTimeout(1600);
await p.click('text=My Own Computer'); await p.waitForTimeout(600);
await p.locator('text=选择电脑').first().click(); await p.waitForTimeout(800);
await p.locator('text=breeze-cobra-99').last().click(); await p.waitForTimeout(700);
await p.click('text=下一步'); await p.waitForTimeout(1600);
await p.fill('input[placeholder="marketing-expert"]','Bill-Bain');
await p.fill('input[placeholder="Research Agent"]','Bill Bain');
const ta=await p.$('textarea'); if(ta) await ta.fill('贝恩公司（Bain & Company）创始人 Bill Bain。');
await p.locator('text=使用运行时默认模型').first().click(); await p.waitForTimeout(700);
await p.getByText('手动输入',{exact:true}).click(); await p.waitForTimeout(700);
await p.fill('input[placeholder="输入模型 ID"]','opus');
await p.waitForTimeout(400);
await p.screenshot({path:'./shots/bb-ready.png'});
// scope create button to dialog (footer)
const btns = p.getByRole('button',{name:'创建 Agent'});
await btns.last().click();
await p.waitForTimeout(7000);
await p.screenshot({path:'./shots/bb-created.png'});
const t=(await p.innerText('body')).replace(/\n{2,}/g,'\n');
console.log('URL:',p.url());
console.log('has Bill Bain?', t.includes('Bill Bain'));
console.log('AGENTS line:', (t.match(/AGENTS · \d+/)||[''])[0]);
await b.close();
