import pkg from '/root/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.js';
const { chromium } = pkg;
const b = await chromium.launch();
const ctx = await b.newContext({ storageState:'./.state.json', locale:'en-US', viewport:{width:1440,height:900}, deviceScaleFactor:2 });
const p = await ctx.newPage();
await p.goto('https://app.syfo.ai/s/mini-pc-on-syfo/members',{waitUntil:'networkidle',timeout:50000});
await p.waitForTimeout(3000);
const t=(await p.innerText('body')).replace(/\n{2,}/g,'\n');
console.log('AGENTS line:', (t.match(/AGENTS · \d+/)||[''])[0]);
console.log('has guide-en?', t.includes('guide-en'));
console.log('has Guide?', /\bGuide\b/.test(t));
console.log('has 导览助手?', t.includes('导览助手'));
await b.close();
