import pkg from '/root/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.js';
const { chromium } = pkg;
const SLUG='mini-pc-on-syfo';
const b = await chromium.launch();
const ctx = await b.newContext({ storageState: './.state.json', locale:'zh-CN', viewport:{width:1440,height:900}, deviceScaleFactor:2 });
const p = await ctx.newPage();
await p.goto(`https://app.syfo.ai/s/${SLUG}/members`,{waitUntil:'networkidle',timeout:50000});
await p.waitForTimeout(2500);
await (await p.$('text=创建 Agent')).click();
await p.waitForTimeout(1800);
await p.click('text=Syfo Cloud');
await p.waitForTimeout(400);
await p.click('text=下一步');
await p.waitForTimeout(1800);
await p.fill('input[placeholder="marketing-expert"]','guide-helper');
await p.fill('input[placeholder="Research Agent"]','导览助手 Lina');
const ta=await p.$('textarea'); if(ta) await ta.fill('Syfo 教程示例云端 Agent：演示如何接收任务、做小研究并产出成果卡片。');
await p.screenshot({path:'./shots/17-create-agent-filled.png'});
await p.click('button:text-is("创建 Agent")');
await p.waitForTimeout(5000);
console.log('URL:', p.url());
await p.screenshot({path:'./shots/18-agent-created.png'});
const t=(await p.innerText('body')).replace(/\n{2,}/g,'\n');
console.log('has guide-helper?', t.includes('guide-helper')||t.includes('导览助手'));
console.log(t.slice(0,300));
await b.close();
