import pkg from '/root/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.js';
const { chromium } = pkg;
const SLUG='mini-pc-on-syfo';
const b = await chromium.launch();
const ctx = await b.newContext({ storageState: './.state.json', locale:'zh-CN', viewport:{width:1440,height:900}, deviceScaleFactor:2 });
const p = await ctx.newPage();
await p.goto(`https://app.syfo.ai/s/${SLUG}/inbox`,{waitUntil:'networkidle',timeout:50000});
await p.waitForTimeout(2500);
await p.click('[aria-label="新建频道"]',{force:true});
await p.waitForTimeout(2000);
await p.screenshot({path:'./shots/14-new-channel-dialog.png'});
console.log('=== NEW CHANNEL DIALOG (tail) ===');
console.log((await p.innerText('body')).replace(/\n{2,}/g,'\n').slice(-800));
await b.close();
